---
# local 환경
spring:
  config.activate.on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지

---
# test 환경
spring:
  config.activate.on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지

---
# prod 환경