spring:
  config.import: file:.env[.properties]
  
---
# local 환경
spring:
  config.activate.on-profile: local
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    admin: ${ADMIN_TOKEN}
    owner: ${OWNER_TOKEN}

---
# test 환경
spring:
  config.activate.on-profile: test
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    admin: ${ADMIN_TOKEN}
    owner: ${OWNER_TOKEN}