spring:
  config.activate.on-profile: key
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    master: ${MASTER_TOKEN}
    manager: ${MANAGER_TOKEN}
    owner: ${OWNER_TOKEN}
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}