spring:
  config:
    import:
      - file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml
      - classpath:./properties/key.yml
  profiles:
    group:
      local: local, key
      test: test, key
      prod: prod, key
    active: ${ACTIVE_VAL}
  application:
    name: order-management-platform

---
# local 설정
spring:
  config.activate.on-profile: local
  devtools:
    livereload:
      enabled: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true

---
# test 환경
spring:
  config.activate.on-profile: test

---
# prod 환경
spring:
  config.activate.on-profile: prod
logging:
  file:
    path: logs
