spring:
  config:
    import:
      - file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml
      - classpath:./properties/key.yml
  profiles:
    active: ${ACTIVE_VAL}
  application:
    name: order-management-platform

---
# local 설정
spring:
  config.activate.on-profile: local
  devtools:
    livereload:
      enabled: true

---
# test 환경
spring:
  config.activate.on-profile: test
