services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    restart: always
networks:
  default:
    external: true
    name: omp