name: docker deploy
on:
  push:
    branches: self-hosted
jobs:
  deploy:
    runs-on: ubuntu-latest #self-hosted
    steps:
      - name: Execute Server Restart through SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sh ${{ secrets.BACK_DEPLOY }}
