name: CD
on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Execute Server Restart through SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sh ${{ secrets.BACK_DEPLOY }}
