name: docker deploy

on:
  push:
    branches: feat/#82_infra
jobs:
  deploy:
    runs-on: ubuntu-latest #self-hosted
    steps:
      - name: Execute Server Restart through SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script_stop: true
          script: |
            sh ${{ secrets.BACK_DEPLOY }}
