name: docker deploy

on:
  push:
    branches: feat/#82_infra

jobs:
  deploy:
    runs-on: ubuntu-latest #self-hosted

    steps:
      - name: Execute Server Restart through SSH
        uses: appleboy/ssh-action@@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            sh ${{ secrets.BACK_DEPLOY }}
